/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Data;
import controller.MyCellRenderer;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.io.File;
import java.util.HashMap;

/**
 * Esta clase pinta la ventana grafica
 * @author Fernando
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    DefaultTableModel model;

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        vaciarTabla();
        setLocationRelativeTo(null);
        getContentPane().setBackground(new Color(237, 242, 244));
    }

    /**
     * Este metodo permite vaciar el modelo de la tabla
     */
    private void vaciarTabla() {
        int rows = tablaDatos.getRowCount();
        model = (DefaultTableModel) tablaDatos.getModel();
        for (int i = 0; i < rows; i++) {
            model.removeRow(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelRuta = new javax.swing.JTextField();
        btnElegir = new javax.swing.JButton();
        btnExtraer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelRuta.setBorder(BorderFactory.createLineBorder(Color.BLACK));
        labelRuta.setFont(new Font("Arial", Font.BOLD, 14));
        labelRuta.setBackground(new Color(55, 63, 81));
        labelRuta.setForeground(Color.white);

        btnElegir.setText("...");
        btnElegir.setFont(new Font("Arial", Font.BOLD, 14));
        btnElegir.setBackground(new Color(88, 164, 176));
        btnElegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElegirActionPerformed(evt);
            }
        });

        btnExtraer.setText("Extraer");
        btnExtraer.setFont(new Font("Arial", Font.BOLD, 14));
        btnExtraer.setBackground(new Color(88, 164, 176));
        btnExtraer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExtraerActionPerformed(evt);
            }
        });

        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                        {null, null},
                        {null, null},
                        {null, null},
                        {null, null}
                },
                new String[]{
                        "Clave", "Valor"
                }
        ) {
            Class[] types = new Class[]{
                    String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }
            boolean[] canEdit = new boolean[]{
                    false, false, false, false, false
            };

        });
        jScrollPane1.setViewportView(tablaDatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(labelRuta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(btnElegir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(btnExtraer)
                                .addGap(30, 30, 30))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(btnElegir)
                                                        .addComponent(btnExtraer)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(34, 34, 34)
                                                .addComponent(labelRuta, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnElegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElegirActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Imágenes", "jpg", "jpeg", "png", "bmp", "gif"));
        if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            labelRuta.setText(file.getAbsolutePath());
        }
    }


    private void btnExtraerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExtraerActionPerformed
        //comprobamos que el campo de la ruta no esta vacio
        if(labelRuta.getText().equals("")){
            return;
        }
        HashMap<String, String> metadataMap = Data.extractImageMetadata(labelRuta.getText());
        //comprobamos que la ruta es correcta
        if(metadataMap == null){
            JOptionPane.showMessageDialog(this,"La ruta no es valida","Error",JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Limpiar la tabla antes de agregar nuevos datos
        DefaultTableModel model = (DefaultTableModel) tablaDatos.getModel();

        model.setRowCount(0);

        // Agregar cada fila de datos a la tabla
        for (String key : metadataMap.keySet()) {
            model.addRow(new Object[] { key, metadataMap.get(key) });
        }
        //le ponemos los colores a la tabla
        tablaDatos.getColumnModel().getColumn(0).setCellRenderer(new MyCellRenderer());
        tablaDatos.getColumnModel().getColumn(1).setCellRenderer(new MyCellRenderer());



    }//GEN-LAST:event_btnExtraerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElegir;
    private javax.swing.JButton btnExtraer;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    private javax.swing.JTextField labelRuta;
    // End of variables declaration//GEN-END:variables
}
